name: ludo
description: Jogo ludo feito com Flutter e Flame.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flame: ^0.27.0
  hive_flutter: ^0.3.0+2
  hive: ^1.4.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

